### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nonmetalhail** [nonmetalhail/plants#1]
- [ ] finish adding plant data
- [x] add a way to mix-in taxonomy entries for items that cannot be found in the gbif database
- [x] add visual indicator of a plant instead of just link in the chain
- [x] add info tooltip
- [ ] add varietals, forms, etc
- [ ] add hybrids - I think we should add the hybrid off a single parent and then manually push a new link with the parent as the other parent and target as the hybrid
- [ ] add images
- [x] text measurement to better size/space the entries
- [x] sorting

================
- [ ] try converting to lit html
